# Generated by Django 3.2.4 on 2021-06-11 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_exp', models.CharField(max_length=50)),
                ('tech_exp_text', models.CharField(blank=True, max_length=255)),
                ('tech_founder', models.CharField(max_length=50)),
                ('tech_founder_text', models.CharField(blank=True, max_length=255)),
                ('startup_stage', models.CharField(max_length=50)),
                ('startup_stage_text', models.CharField(blank=True, max_length=255)),
                ('startup_description', models.TextField(max_length=1000)),
                ('access_freq', models.CharField(max_length=50)),
                ('access_freq_text', models.CharField(blank=True, max_length=255)),
                ('tech_challenge', models.CharField(max_length=50)),
                ('tech_challenge_description', models.TextField(max_length=1000)),
                ('roadblocks', models.CharField(max_length=50)),
                ('roadblocks_text', models.CharField(blank=True, max_length=255)),
                ('timeline', models.CharField(max_length=50)),
                ('timeline_text', models.CharField(blank=True, max_length=255)),
                ('subscriber_first_name', models.CharField(max_length=100)),
                ('subscriber_last_name', models.CharField(max_length=100)),
                ('subscriber_email', models.EmailField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
