# Generated by Django 3.2.4 on 2021-06-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_image_expert_headshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='designation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
